name: gcc-build

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-linux-lqx"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out linux-tkg repository
        uses: actions/checkout@v3
        with:
          repository: damentz/linux-lqx
          path: linux-lqx
      - name: Prepare for build
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
           sed -i -e "/scripts\/config --disable CONFIG_SCHED_BMQ/i \ \t\tscripts/config --enable CONFIG_CPU_FREQ_GOV_SCHEDUTIL" linux-lqx/PKGBUILD
           sed -i -e "/scripts\/config --disable CONFIG_SCHED_BMQ/i \ \t\tscripts/config --enable CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL" linux-lqx/PKGBUILD
           sed -i -e "/scripts\/config --disable CONFIG_SCHED_BMQ/i \ \t\tscripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE" linux-lqx/PKGBUILD
           sed -i -e "/scripts\/config --disable CONFIG_SCHED_BMQ/i \ \t\tpatch -Np1 -i ../../O3.patch" linux-lqx/PKGBUILD
           curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.1/0013-optimize_harder_O3.patch -o linux-lqx/O3.patch
           cat linux-lqx/PKGBUILD
      - name: Build kernel
        run: |
           cd linux-lqx
           su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-lqx
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
