name: llvm-build

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 18 24 1 *'
env:
  PKGDEST: "/tmp/linux-lqx"
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
#      - name: Set Swap Space
#        uses: pierotofy/set-swap-space@master
#        with:
#          swap-size-gb: 13
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out linux-lqx repository
        uses: actions/checkout@v3
        with:
          repository: damentz/linux-lqx
          path: linux-lqx
      - name: Prepare for build
        run: |
          pacman -Syu --noconfirm base-devel sudo schedtool jq unzip python
          curl -sLJO -H 'Accept: application/octet-stream' \
          "https://${{ secrets.pat }}@api.github.com/repos/mtak-misc/pkgbuild-llvm-git/releases/assets/$( \
          curl -sL https://${{ secrets.pat }}@api.github.com/repos/mtak-misc/pkgbuild-llvm-git/releases/tags/latest \
          | jq '.assets[] | select(.name | contains("llvm")) | .id')" -o llvm-git.zip
          unzip llvm-git.zip
          pacman --noconfirm -U llvm-git*.pkg.tar.zst llvm-libs-git*.pkg.tar.zst
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tpatch -Np1 -i ../../O3.patch' linux-lqx/PKGBUILD
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.7/0013-optimize_harder_O3.patch -o linux-lqx/O3.patch
          sed -i -e '/export KBUILD_BUILD_HOST=archlinux/i export llvm_opt="LLVM=1 LLVM_IAS=1"' linux-lqx/PKGBUILD
          sed -i 's/make nconfig/make nconfig ${llvm_opt} /g' linux-lqx/PKGBUILD
          sed -i 's/make xconfig/make xconfig ${llvm_opt} /g' linux-lqx/PKGBUILD
          sed -i 's/make gconfig/make gconfig ${llvm_opt} /g' linux-lqx/PKGBUILD
          sed -i 's/make all/make ${llvm_opt} all/g' linux-lqx/PKGBUILD
          sed -i 's/make LSMOD=$HOME\/.config\/modprobed.db localmodconfig/make LSMOD=$HOME\/.config\/modprobed.db localmodconfig ${llvm_opt} /g' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -d CONFIG_LTO_NONE' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_LTO_CLANG_FULL' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -d CONFIG_LTO_CLANG_THIN' linux-lqx/PKGBUILD
          sed -i 's/gettext/gettext llvm lld clang/g' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -d CONFIG_KCSAN' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_INIT_ON_FREE_DEFAULT_ON' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_INIT_STACK_ALL_ZERO' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -d CONFIG_INIT_STACK_NONE' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_STACK_VALIDATION' linux-lqx/PKGBUILD
          sed -i -e 's/_NUMAdisable=y/_NUMAdisable=n/g' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_NUMA' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NUMA' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e AMD_NUMA' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e X86_64_ACPI_NUMA' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NODES_SPAN_OTHER_NODES' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NUMA_EMU' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e USE_PERCPU_NUMA_NODE_ID' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e ACPI_NUMA' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e ARCH_SUPPORTS_NUMA_BALANCING' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NODES_SHIFT' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config --set-val NODES_SHIFT 5' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NEED_MULTIPLE_NODES' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NUMA_BALANCING' linux-lqx/PKGBUILD
          sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e NUMA_BALANCING_DEFAULT_ENABLED' linux-lqx/PKGBUILD
          cat linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -d CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_CPU_FREQ_GOV_CONSERVATIVE' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_CPU_FREQ_GOV_SCHEDUTIL' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tpatch -Np1 -i ../../../srso2.patch' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tpatch -Np1 -i ../../../srso.patch' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -d CONFIG_CPU_SRSO' linux-lqx/PKGBUILD
#           sed -i -e '/scripts\/config -d CONFIG_SCHED_BMQ/i \ \t\tscripts/config -e CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE' linux-lqx/PKGBUILD
      - name: Build kernel
        run: |
          cd linux-lqx 
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
#           docker run -e USERID=$(id -u $(whoami)) -e GITHUB_TOKEN=${{ secrets.pat }} -v $GITHUB_WORKSPACE:/workspace archlinux:latest /bin/bash /workspace/build.sh
#           cp $GITHUB_WORKSPACE/linux-lqx/*.pkg.tar.zst /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: linux-lqx
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
